using Kards.Ui.Contracts;
using Orc.Game.Cards;

namespace Kards.Ui.OrcBridge;

/// <summary>How many copies of one card a deck may hold. The engine does not police this; KARDS does.</summary>
public static class DeckRules
{
    /// <summary>Tokens are generated by effects, so a deck never holds one.</summary>
    public const int MaxCopiesPerCard = 3;
    public const int DeckSize = 30;
    public const int MinUnits = 8;
}

/// <summary>
/// Builds a playable deck from the cards the engine can represent.
///
/// The point of this is that a deck is a real game object, not a list of whatever happened to
/// compile: it must be a fixed size, respect the copy limit, hold a usable spread of units and
/// orders, and be able to pay for itself. A deck of thirty orders is technically valid and
/// completely unplayable.
/// </summary>
public static class DeckBuilder
{
    /// <summary>
    /// Builds a playable deck. Two properties matter beyond legality:
    ///
    /// - **Copy spread.** A real deck wants a handful of cheap units, not fifteen random ones, so
    ///   the opening hand is not a dead turn. The first turn grants a single command point, so a
    ///   deck without one-cost units cannot open at all — measured at 10% of hands before this
    ///   weighting, which is not playable in any meaningful sense.
    /// - **Affordability floor.** The opening half of the deck is drawn from cards cheap enough to
    ///   be worth deploying early; the back half can be expensive.
    ///
    /// Deterministic for a given seed, which the contract tests rely on.
    /// </summary>
    public static IReadOnlyList<string> Build(IReadOnlyList<CardDefinitionEntry> pool, int seed, int size = DeckRules.DeckSize)
    {
        var units = pool.Where(e => e.Definition.Category == CardCategory.Unit).ToArray();
        var orders = pool.Where(e => e.Definition.Category == CardCategory.Command).ToArray();
        if (units.Length == 0) throw new InvalidOperationException("The pool has no units to build a deck from.");

        var random = new Random(seed);
        var deck = new List<string>(size);
        var used = new Dictionary<string, int>(StringComparer.Ordinal);

        // A quarter of the deck is cheap units (cost 1-2), then mid-cost bodies, then the rest of
        // the units, then orders. Without the cheap step the first turn is usually unplayable.
        var cheap = units.Where(e => Cost(e) <= CheapCostCeiling).ToArray();
        var rest = units.Where(e => Cost(e) > CheapCostCeiling).ToArray();
        var unitTarget = Math.Clamp(size / 2, 4, size - 4);
        var cheapTarget = Math.Min(cheap.Length * DeckRules.MaxCopiesPerCard, Math.Max(4, size / 6));
        Take(cheap, cheapTarget, used, deck, random);
        // The cheap step already put cards in the deck, so the rest tops the unit quota up.
        Take(rest, Math.Max(0, unitTarget - deck.Count), used, deck, random);
        Take(orders, size - deck.Count, used, deck, random);
        // A pool too small to fill the deck is topped up from whatever is left rather than short.
        if (deck.Count < size) Take(pool, size - deck.Count, used, deck, random);
        return deck;
    }

    /// <summary>A unit at or under this cost is worth having several of, for the opening turns.</summary>
    private const int CheapCostCeiling = 2;

    private static int Cost(CardDefinitionEntry entry) => entry.Definition.DeployCost;

    /// <summary>
    /// Appends up to <paramref name="count"/> more cards from <paramref name="source"/>. The count
    /// is an increment, not a deck total: callers add units first, then orders, and each call only
    /// tops the deck up by what it was asked for.
    /// </summary>
    private static void Take(IReadOnlyList<CardDefinitionEntry> source, int count,
        Dictionary<string, int> used, List<string> deck, Random random)
    {
        var target = deck.Count + count;
        // Shuffle once so the pick is stable for a seed, then take in that order.
        foreach (var entry in source.OrderBy(_ => random.Next()))
        {
            if (deck.Count >= target) return;
            if (used.TryGetValue(entry.Id, out var taken) && taken >= DeckRules.MaxCopiesPerCard) continue;
            used[entry.Id] = taken + 1;
            deck.Add(entry.Id);
        }
    }

    /// <summary>
    /// Reports why a deck cannot be played, or an empty list when it can. Kept separate from
    /// <see cref="Build"/> so a caller can hand a player an authored deck and get told what is
    /// wrong with it rather than a silent reshuffle.
    /// </summary>
    public static IReadOnlyList<string> Validate(IReadOnlyList<string> deck, IReadOnlyList<CardDefinitionEntry> pool)
    {
        var problems = new List<string>();
        if (deck.Count == 0) { problems.Add("牌组为空"); return problems; }
        if (deck.Count != DeckRules.DeckSize) problems.Add($"牌组应为 {DeckRules.DeckSize} 张，实为 {deck.Count} 张");

        var known = pool.Select(e => e.Id).ToHashSet(StringComparer.Ordinal);
        foreach (var id in deck.Where(id => !known.Contains(id)).Distinct())
            problems.Add($"未知卡牌 {id}");

        foreach (var group in deck.GroupBy(x => x, StringComparer.Ordinal)
            .Where(g => g.Count() > DeckRules.MaxCopiesPerCard))
            problems.Add($"{group.Key} 有 {group.Count()} 张，超过上限 {DeckRules.MaxCopiesPerCard}");

        var category = pool.Where(e => deck.Contains(e.Id)).ToDictionary(e => e.Id, e => e.Definition.Category);
        var units = deck.Count(id => category.GetValueOrDefault(id) == CardCategory.Unit);
        if (units < DeckRules.MinUnits)
            problems.Add($"单位只有 {units} 张，至少需要 {DeckRules.MinUnits} 张");
        if (deck.Any(id => category.GetValueOrDefault(id) == CardCategory.Command) == false)
            problems.Add("牌组里没有指令卡");
        return problems;
    }
}
